app_name="gitsync"
app_secret="$app_secret" #用于对敏感数据进行加密

[log]
enabled=true
log_level="debug" # error
output_type="console" # console|file
filename="logs.log" # console|file

[ext]
[ext.sync]
# 11 分钟, 默认2分钟
time_interval=20000
# 11 天, 默认7天
time_offset=-98
repo_dir="repos"

from_branch="master"
from_user_pass=["baiyunhui","$from_user_pass","baiyunhui@yuanben.org"]

to_branch="master"
to_user_pass=["kooksee","$to_user_pass","kooksee@163.com"]

[[ext.sync.cfg]]
from_repo="https://git.dev.yuanben.org/scm/trn/datastore_frontend.git"
to_repo="https://github.com/kooksee/datastore_frontend.git"

#[[ext.sync.cfg]]
#from_repo="https://git.dev.yuanben.org/scm/~baiyunhui/portal.git"
#to_repo="https://github.com/kooksee/portal.git"
