app_name="gitsync"

[log]
enabled=true
log_level="debug"
output_type="console" # console|file

[ext]
[ext.sync]
[[ext.sync.cfg]]
name="beepkg"
desc="项目描述"
from_repo=""
to_rep=""
time_interval="60d"


