[log]
enabled=true
log_level="debug"
output_type="console" # console|file
filename="logs.log" # console|file

[ext]
[ext.sync]
repo_dir="repos"
[[ext.sync.cfg]]
time_interval=60

repo_name=""

from_repo=""
from_branch="master"

to_repo=""
to_branch="master"



